FORMAT: 1A
HOST: http://api.sofiafest.com

# sofia-swing API

Sofia-Swing is an API that allows for retrieveing information about swing dance events.


## Events [/orgs/{o_id}/events]

All API calls for listing events must provide the `id` of the organisation that owns the events.

### List all events [GET]

+ Parameters
    + o_id (number) - The organisation's id

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "from_date": "2015-08-05T08:40:51.620Z",
                "to_date": "2015-08-10T08:40:51.620Z",
                "name": "Sofia Swing Dance Festival",
                "description": "The biggest swing dance event in Bulgaria.",
                "organiser_id": 5,
                "country_code": "BUL",
                "city": "Sofia"
            },
            
            {
                "id": 2,
                "from_date": "2015-09-05T08:40:51.620Z",
                "to_date": "2015-09-10T08:40:51.620Z",
                "name": "Veliko Tarnovo Swing Dance Festival",
                "description": "History meets dance",
                "organiser_id": 7,
                "country_code": "BUL",
                "city": "Veliko Tarnovo"
            }
        ]

### Create a new event [POST]

+ from_date - Starting date of the festival
+ to_date - End date of the festival
+ name - The name of the festival
+ country_code - The country code of the hosting country
+ city - The city of the festival

+ Parameters
    + o_id (number) - The organisation's id

+ Request (application/json)

            {
                "from_date": "2015-09-05T08:40:51.620Z",
                "to_date": "2015-09-10T08:40:51.620Z",
                "name": "Veliko Tarnovo Swing Dance Festival",
                "description": "History meets dance",
                "country_code": "BUL",
                "city": "Veliko Tarnovo"
            }

+ Response 201

    + Headers

            Location: /orgs/20/events/5

### List all people for a given event [GET /orgs/{o_id}/events/{e_id}/people]

+ Parameters
    + o_id (number) - The organisation's id
    + e_id (number) - The id of the event

+ Response 200 (application/json)

        {
            "event_id": 20,
            "people": [
                {
                    "id": 1,
                    "userId": 5,
                    "firstName": "Britney",
                    "lastName": "Spears"
                },
                {
                    "id": 2,
                    "userId": 10,
                    "firstName": "Lady",
                    "lastName": "Gaga"
                },
                {
                    "id": 3,
                    "userId": 15,
                    "firstName": "Ivan",
                    "lastName": "Ivanov"
                },
                {
                    "id": 4,
                    "userId": 50,
                    "firstName": "Spas",
                    "lastName": "Spasov"
                }
            ]
        }