package bg.lindyhop.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import bg.lindyhop.entities.Event;
import bg.lindyhop.entities.FeedItem;
import bg.lindyhop.entities.FeedItemUrl;

import bg.lindyhop.dao.EventDao;
import bg.lindyhop.dao.FeedItemDao;
import bg.lindyhop.dao.FeedItemUrlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig feedItemDaoConfig;
    private final DaoConfig feedItemUrlDaoConfig;

    private final EventDao eventDao;
    private final FeedItemDao feedItemDao;
    private final FeedItemUrlDao feedItemUrlDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        feedItemDaoConfig = daoConfigMap.get(FeedItemDao.class).clone();
        feedItemDaoConfig.initIdentityScope(type);

        feedItemUrlDaoConfig = daoConfigMap.get(FeedItemUrlDao.class).clone();
        feedItemUrlDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        feedItemDao = new FeedItemDao(feedItemDaoConfig, this);
        feedItemUrlDao = new FeedItemUrlDao(feedItemUrlDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(FeedItem.class, feedItemDao);
        registerDao(FeedItemUrl.class, feedItemUrlDao);
    }
    
    public void clear() {
        eventDaoConfig.getIdentityScope().clear();
        feedItemDaoConfig.getIdentityScope().clear();
        feedItemUrlDaoConfig.getIdentityScope().clear();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public FeedItemDao getFeedItemDao() {
        return feedItemDao;
    }

    public FeedItemUrlDao getFeedItemUrlDao() {
        return feedItemUrlDao;
    }

}
