# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'SwingAout Festival' do
    pod 'AFOAuth2Manager'
    pod 'SDWebImage'
    pod 'GoogleMaps'
    pod 'MBAutoGrowingTextView', '~> 0.1.0'
end


